steps:
  - name: 'golang:1.11.5-stretch'
    entrypoint: 'go'
    args: ['build', '.']
    env: ['GO111MODULE=on']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '--tag=gcr.io/$PROJECT_ID/sinmetal/gatling-nail-gun/$BRANCH_NAME:$COMMIT_SHA', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ["push", "gcr.io/$PROJECT_ID/sinmetal/gatling-nail-gun/$BRANCH_NAME:$COMMIT_SHA"]